# Generated by Django 3.1.4 on 2021-01-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='area',
            field=models.CharField(choices=[(1, '300m'), (2, '500m'), (3, '1000m'), (4, '2000m'), (5, '3000m')], max_length=100),
        ),
    ]
