# Generated by Django 3.1.4 on 2021-01-31 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20210125_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmodel',
            name='genre',
            field=models.CharField(choices=[('G001', '居酒屋'), ('G002', 'ダイニングバー・バル'), ('G003', '創作料理'), ('G004', '和食'), ('G005', '洋食'), ('G006', 'イタリアン・フレンチ'), ('G007', '中華'), ('G008', '焼肉・ホルモン'), ('G017', '韓国料理'), ('G009', 'アジア・エスニック料理'), ('G010', '各国料理'), ('G011', 'カラオケ・パーティ'), ('G012', 'バー・カクテル'), ('G013', 'ラーメン'), ('G016', 'お好み焼き・もんじゃ'), ('G014', 'カフェ・スイーツ'), ('G015', 'その他グルメ')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
